# Generated by Django 5.0.2 on 2024-07-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0005_remove_course_course_main_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_subscription_type',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Basic')], default='1', max_length=2),
        ),
    ]
