# Generated by Django 5.0.2 on 2024-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0006_alter_videos_video_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('1', 'Academics Excellence'), ('2', 'English Language'), ('3', 'Business English'), ('4', 'General Knowledge'), ('5', 'Professional Knowledge'), ('6', 'Sports'), ('7', 'Psychology & Mindset'), ('8', 'Food & Drinks'), ('9', 'Health, Beauty & Fashion'), ('10', 'CV & Interview Techniques'), ('11', 'Entrepreurship & Investing')], default='2', max_length=2),
        ),
    ]
