# Generated by Django 5.0.2 on 2024-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_full_name', models.CharField(max_length=50)),
                ('member_email_address', models.CharField(max_length=100)),
            ],
        ),
    ]
