# Generated by Django 5.0.2 on 2024-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_email_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_full_name',
        ),
        migrations.AddField(
            model_name='member',
            name='email_address',
            field=models.EmailField(default='error@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_courses_duration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='member',
            name='recurring_subscription',
            field=models.BooleanField(default=True),
        ),
    ]
