# Generated by Django 5.0.2 on 2024-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_member_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='recurring_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
