# Generated by Django 5.0.2 on 2024-06-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_url', models.CharField(max_length=20)),
                ('course_name', models.CharField(default='default_course_name', max_length=100)),
                ('course_category', models.CharField(choices=[('1', 'Academics_Language_Learning'), ('2', 'Health & Lifestyle'), ('3', 'Social & Entertainment'), ('4', 'Career & Finance')], default='1', max_length=2)),
                ('course_title', models.CharField(default='default_title', max_length=100)),
                ('course_banner', models.ImageField(default='Muscle_Building/Course_Banner/Muscle_Building_Course_Banner_1.jpg', null=True, upload_to='Muscle_Building/Course_Banner')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question_num', models.CharField(default='0', max_length=2)),
                ('faq_question', models.CharField(default='default_faq_question', max_length=100)),
                ('faq_answer', models.CharField(default='default_faq_answer', max_length=500)),
                ('course_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_videos.course')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='default_title', max_length=100)),
                ('video_subscription_type', models.CharField(choices=[('1', 'Free'), ('2', 'Basic'), ('3', 'Premium')], default='1', max_length=2)),
                ('video_series_name', models.CharField(default='default_series_name', max_length=20)),
                ('video_series', models.CharField(default='0', max_length=2)),
                ('video_episode', models.CharField(default='0', max_length=2)),
                ('video_icon', models.ImageField(default='Muscle_Building/Video_Icon/Muscle_Building_Video_Icon_2.jpg', upload_to='Muscle_Building/Video_Icon')),
                ('video_video', models.FileField(default='Muscle_Building/Video_Video/Muscle_Building_Video_Video_1.mp4', null=True, upload_to='Muscle_Building/Video_Video')),
                ('video_duration', models.CharField(blank=True, max_length=5, null=True)),
                ('course_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_videos.course')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
