# Generated by Django 5.0.2 on 2024-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
