# Generated by Django 5.0.2 on 2024-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_author',
            field=models.CharField(default='default_course_author', max_length=100),
        ),
    ]
