# Generated by Django 5.0.2 on 2024-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0002_course_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='settings.MEDIA_ROOT/static/course_image/Muscle_Building_Image_1.jpg', null=True, upload_to='course_image'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_sub_image',
            field=models.ImageField(default='settings.MEDIA_ROOT/static/course_image/Muscle_Building_Image_3.jpg', null=True, upload_to='course_sub_image'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='default_title', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(default='default_category', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(default='settings.MEDIA_ROOT/static/course_image/Muscle_Building_Video_1.mp4', null=True, upload_to='course_video'),
        ),
    ]
