# Generated by Django 5.0.6 on 2024-05-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0003_course_course_image_course_course_sub_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='course_image/Muscle_Building_Image_1.jpg', null=True, upload_to='course_image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_sub_image',
            field=models.ImageField(default='course_image/Muscle_Building_Image_3.jpg', null=True, upload_to='course_sub_image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(default='course_video/Muscle_Building_Video_1.mp4', null=True, upload_to='course_video'),
        ),
    ]
