# Generated by Django 5.0.2 on 2024-07-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0003_alter_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_descriptions',
            field=models.CharField(default='default_descriptions', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='course_main_banner',
            field=models.ImageField(default='Muscle_Building/Course_Main_Banner/Muscle_Building_Course_Banner_1.jpg', null=True, upload_to='Muscle_Building/Course_Main_Banner'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('1', 'Academics Excellence'), ('2', 'English Language'), ('3', 'Business English'), ('4', 'General Knowledge'), ('5', 'Professional Knowledge'), ('6', 'Sports'), ('7', 'Health & Wellness'), ('8', 'Food & Drinks'), ('9', 'Health, Beauty & Fashion'), ('10', 'CV & Interview Techniques'), ('11', 'Entrepreurship & Investing')], default='2', max_length=2),
        ),
    ]
