# Generated by Django 5.0.2 on 2024-07-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0004_course_course_descriptions_course_course_main_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_main_banner',
        ),
    ]
