# Generated by Django 5.0.6 on 2024-05-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0004_alter_course_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_video',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_sub_image',
            field=models.ImageField(default='course_image/Muscle_Building_Image_4.jpg', null=True, upload_to='course_sub_image'),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='default_title', max_length=100)),
                ('video_essay', models.CharField(default='default_essay', max_length=100)),
                ('video_series', models.CharField(default='default_series', max_length=20)),
                ('video_episode', models.CharField(default='default_episode', max_length=20)),
                ('video_image', models.ImageField(default='video_image/Muscle_Building_Image_2.jpg', null=True, upload_to='video_image')),
                ('video_video', models.FileField(default='video_video/Muscle_Building_Video_1.mp4', null=True, upload_to='video_video')),
                ('video_watched_duration_current_month_minutes', models.CharField(default='0', max_length=100)),
                ('video_watched_duration_last_month_minutes', models.CharField(default='0', max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_videos.course')),
            ],
        ),
    ]
