# Generated by Django 5.0.6 on 2024-05-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0005_remove_course_course_video_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
