# Generated by Django 5.0.2 on 2024-05-29 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0006_rename_videos_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_image',
            new_name='course_banner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_sub_image',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.CharField(choices=[('1', 'Academics_Language_Learning'), ('2', 'Health & Lifestyle'), ('3', 'Social & Entertainment'), ('4', 'Career & Finance')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question_num', models.CharField(default='0', max_length=2)),
                ('faq_question', models.CharField(default='default_faq_question', max_length=100)),
                ('faq_answer', models.CharField(default='default_faq_answer', max_length=500)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_videos.course')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(default='default_title', max_length=100)),
                ('video_subscription_type', models.CharField(choices=[('1', 'Free'), ('2', 'Basic'), ('3', 'Premium'), ('4', 'One Off')], default='1', max_length=2)),
                ('video_series_name', models.CharField(default='default_series_name', max_length=20)),
                ('video_series', models.CharField(default='0', max_length=2)),
                ('video_episode', models.CharField(default='0', max_length=2)),
                ('video_image', models.ImageField(default='video_image/Muscle_Building_Image_2.jpg', null=True, upload_to='video_image')),
                ('video_video', models.FileField(default='video_video/Muscle_Building_Video_1.mp4', null=True, upload_to='video_video')),
                ('video_essay', models.TextField(default='default_video_essay')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_videos.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
