# Generated by Django 5.0.2 on 2024-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0007_rename_course_image_course_course_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Videos'},
        ),
    ]
