# Generated by Django 5.0.2 on 2024-05-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0008_alter_course_options_alter_faqs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(default='Muscle_Building/Course_Banner/Muscle_Building_Image_1.jpg', null=True, upload_to='course_image'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_image',
            field=models.ImageField(default='Muscle_Building/Video_Image/Muscle_Building_Video_Icon_2.jpg', null=True, upload_to='video_image'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_video',
            field=models.FileField(default='Muscle_Building/Video_Video/Muscle_Building_Video_1.mp4', null=True, upload_to='video_video'),
        ),
    ]
