# Generated by Django 5.0.2 on 2024-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0009_alter_course_course_banner_alter_videos_video_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_image',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_icon',
            field=models.ImageField(default='Muscle_Building/Video_Icon/Muscle_Building_Video_Icon_2.jpg', upload_to='Muscle_Building/Video_Icon'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(default='Muscle_Building/Course_Banner/Muscle_Building_Course_Banner_1.jpg', null=True, upload_to='Muscle_Building/Course_Banner'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_video',
            field=models.FileField(default='Muscle_Building/Video_Video/Muscle_Building_Video_Video_1.mp4', null=True, upload_to='Muscle_Building/Video_Video'),
        ),
    ]
