# Generated by Django 5.0.2 on 2024-05-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0010_remove_videos_video_image_videos_video_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_subscription_type',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Basic'), ('3', 'Premium')], default='1', max_length=2),
        ),
    ]
