# Generated by Django 5.0.2 on 2024-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0011_alter_videos_video_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.CharField(default='default_url', max_length=20),
        ),
    ]
