# Generated by Django 5.0.2 on 2024-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0012_course_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='course_name',
            new_name='course_url',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='course_name',
            new_name='course_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='default_course_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_url',
            field=models.CharField(max_length=20),
        ),
    ]
