# Generated by Django 5.0.2 on 2024-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0013_rename_course_name_faqs_course_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_essay',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
