# Generated by Django 5.0.2 on 2024-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0014_remove_videos_video_essay_videos_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_duration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
