# Generated by Django 5.0.2 on 2024-06-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0015_alter_videos_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='course_url',
            new_name='course',
        ),
    ]
