# Generated by Django 5.0.2 on 2024-06-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_videos', '0016_rename_course_url_faqs_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqs',
            old_name='course',
            new_name='course_url',
        ),
    ]
