name: Backend Deployment

on:
  push:
    branches:
      - deploy

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }} "echo SSH connection established"

    - name: Deploy code to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }} "
        if [ -d '/var/www/Scientific-Methodology-Backend/.git' ]; then
          cd /var/www/Scientific-Methodology-Backend && git pull origin deploy && cd population_scripts_course_videos/ && python3 run_all_population_scripts.py;
        else
          git clone --branch deploy git@github.com:${{ github.repository }}.git /var/www/Scientific-Methodology-Backend;
        fi"
