name: Scientific Methodology Produciton

on:
  push:
   branches: production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Rsync Deployer
        uses: imajeetyadav/rsync-deployer@1.0.0
        with:
          HOST: ${{ secrets.PROD_SSH_HOST }}
          USERNAME: ${{ secrets.PROD_USERNAME }}
          KEY: ${{ secrets.PROD_SSH_PRIVATEKEY }}
          SOURCE_PATH: "."
          TARGET_PATH: "/var/www/backend"
          PORT: 22
          RSYNC_PARAMETERS: ""
          DELETE_OPTION: "false"
          EXCLUDE_LIST: ".git, .github"
          DRY_RUN: "false"

      - name: Post Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATEKEY }}
          port: 22
          script: |
            cd /var/www/backend/population_scripts_course_videos && python3 run_all_population_scripts.py
            cd /var/www/backend
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            sudo systemctl restart backend.service
